name: PR_Unit_Integration_Test-Dev
env:
  DOTNET_VERSION: '7.0.x'
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  test:
    name: change secret
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: pattubala/dotnet_code_test
          
      - name: Get var vaule
        id: variables
        run: echo "::set-output name=vartoken::${{ vars.VARIABLE }}"
        
      - name: Get secret value
        id: secrets
        run: echo "::set-output name=token::${{ secrets.SECRET }}"

      - name: sed command
        run: |
          sed -i '5s/"uuid": ""/"uuid": "'${{ steps.variables.outputs.vartoken }}'"/' sample1 sample2
          cat sample1
          
      - name: sed command
        run: |
          sed -i '5s/"uuid": ""/"uuid": "'${{ steps.secrets.outputs.token }}'"/' sample sample1 sample2
          cat sample
          
      - name: print file
        run: cat sample
      
    
