name: PR_Unit_Integration_Test-Dev
env:
  DOTNET_VERSION: '7.0.x'
on:
  workflow_dispatch:
  pull_request:
    branches:
      - develop

jobs:
  test:
    name: change secret
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: pattubala/dotnet_code_test
      - name: sed command
        run: |
         sed -i '8s/.*/$SECRET/' sample sample1 sample2
      - name: print file
        run: cat sample
      
    
