name: PR_Unit_Integration_Test-Dev
env:
  DOTNET_VERSION: '7.0.x'
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  test:
    name: change secret
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: pattubala/dotnet_code_test
      - name: Get secret value
        id: secrets
        run: echo "::set-output name=token::${{ secrets.TOKEN }}"
 
      - name: sed command
        run: |
          token="${{ steps.secrets.outputs.token }}"
          sed -i '5s//"uuid": ""/"uuid": "'"$token"'"/' sample sample1 sample2
          
      - name: print file
        run: cat sample
      
    
